---
title: "trabajo 2"
author: "Dayanne Centti"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
Pobreza=import("https://docs.google.com/spreadsheets/d/1JRF8isBWKfvaRauzmIH-XLspC-eNdUEA4b-VJyjBiqM/edit#gid=1208926362")
```

```{r}
Pobreza$`"Indicator Code"`=NULL
Pobreza$`"Indicator Name"`=NULL
Pobreza$`"1960"`=NULL
Pobreza$`"1961"`=NULL
Pobreza$`"1962"`=NULL
Pobreza$`"1963"`=NULL
Pobreza$`"1964"`=NULL
Pobreza$`"1965"`=NULL
Pobreza$`"1966"`=NULL
Pobreza$`"1967"`=NULL
Pobreza$`"1968"`=NULL
Pobreza$`"1969"`=NULL
Pobreza$`"1970"`=NULL
Pobreza$`"1971"`=NULL
Pobreza$`"1972"`=NULL
Pobreza$`"1973"`=NULL
Pobreza$`"1974"`=NULL
Pobreza$`"1975"`=NULL
Pobreza$`"1976"`=NULL
Pobreza$`"1977"`=NULL
Pobreza$`"1978"`=NULL
Pobreza$`"1979"`=NULL
Pobreza$`"1980"`=NULL
Pobreza$`"1981"`=NULL
Pobreza$`"1982"`=NULL
Pobreza$`"1983"`=NULL
Pobreza$`"1984"`=NULL
Pobreza$`"1985"`=NULL
Pobreza$`"1986"`=NULL
Pobreza$`"1987"`=NULL
Pobreza$`"1988"`=NULL
Pobreza$`"1989"`=NULL
Pobreza$`"1990"`=NULL
Pobreza$`"1991"`=NULL
Pobreza$`"1992"`=NULL
Pobreza$`"1993"`=NULL
Pobreza$`"1994"`=NULL
Pobreza$`"1995"`=NULL
Pobreza$`"1996"`=NULL
Pobreza$`"1997"`=NULL
Pobreza$`"1998"`=NULL
Pobreza$`"1999"`=NULL
Pobreza$`"2000"`=NULL
Pobreza$`"2001"`=NULL
Pobreza$`"2002"`=NULL
Pobreza$`"2003"`=NULL
Pobreza$`"2004"`=NULL
Pobreza$`"2005"`=NULL
Pobreza$`"2006"`=NULL
Pobreza$`"2007"`=NULL
Pobreza$`"2008"`=NULL
Pobreza$`"2009"`=NULL
Pobreza$`"2010"`=NULL
Pobreza$`"2011"`=NULL
Pobreza$`"2012"`=NULL
Pobreza$`"2013"`=NULL
Pobreza$`"2014"`=NULL
Pobreza$`"2015"`=NULL
Pobreza$`"2016"`=NULL
Pobreza$`"2017"`=NULL
Pobreza$`"2019"`=NULL
Pobreza$`"2020"`=NULL
Pobreza$`"2021"`=NULL
Pobreza$`"2022"`=NULL
Pobreza$`"`=NULL
```

```{r}
library(rio)
Inflacion=import("https://docs.google.com/spreadsheets/d/1QvsCrnXK4eemwv9ovbziYm1qM-NzvzSXYcI9IZtHvjc/edit#gid=638317254")
```

```{r}
Inflacion$`"Indicator Code"`=NULL
Inflacion$`"Indicator Name"`=NULL
Inflacion$`"1960"`=NULL
Inflacion$`"1961"`=NULL
Inflacion$`"1962"`=NULL
Inflacion$`"1963"`=NULL
Inflacion$`"1964"`=NULL
Inflacion$`"1965"`=NULL
Inflacion$`"1966"`=NULL
Inflacion$`"1967"`=NULL
Inflacion$`"1968"`=NULL
Inflacion$`"1969"`=NULL
Inflacion$`"1970"`=NULL
Inflacion$`"1971"`=NULL
Inflacion$`"1972"`=NULL
Inflacion$`"1973"`=NULL
Inflacion$`"1974"`=NULL
Inflacion$`"1975"`=NULL
Inflacion$`"1976"`=NULL
Inflacion$`"1977"`=NULL
Inflacion$`"1978"`=NULL
Inflacion$`"1979"`=NULL
Inflacion$`"1980"`=NULL
Inflacion$`"1981"`=NULL
Inflacion$`"1982"`=NULL
Inflacion$`"1983"`=NULL
Inflacion$`"1984"`=NULL
Inflacion$`"1985"`=NULL
Inflacion$`"1986"`=NULL
Inflacion$`"1987"`=NULL
Inflacion$`"1988"`=NULL
Inflacion$`"1989"`=NULL
Inflacion$`"1990"`=NULL
Inflacion$`"1991"`=NULL
Inflacion$`"1992"`=NULL
Inflacion$`"1993"`=NULL
Inflacion$`"1994"`=NULL
Inflacion$`"1995"`=NULL
Inflacion$`"1996"`=NULL
Inflacion$`"1997"`=NULL
Inflacion$`"1998"`=NULL
Inflacion$`"1999"`=NULL
Inflacion$`"2000"`=NULL
Inflacion$`"2001"`=NULL
Inflacion$`"2002"`=NULL
Inflacion$`"2003"`=NULL
Inflacion$`"2004"`=NULL
Inflacion$`"2005"`=NULL
Inflacion$`"2006"`=NULL
Inflacion$`"2007"`=NULL
Inflacion$`"2008"`=NULL
Inflacion$`"2009"`=NULL
Inflacion$`"2010"`=NULL
Inflacion$`"2011"`=NULL
Inflacion$`"2012"`=NULL
Inflacion$`"2013"`=NULL
Inflacion$`"2014"`=NULL
Inflacion$`"2015"`=NULL
Inflacion$`"2016"`=NULL
Inflacion$`"2017"`=NULL
Inflacion$`"2019"`=NULL
Inflacion$`"2020"`=NULL
Inflacion$`"2021"`=NULL
Inflacion$`"2022"`=NULL
Inflacion$`"`=NULL
```

```{r}
library(rio)
Patentes=import("PATENTES_WIPO.csv")
```
```{r}
Patentes$`Oficina (Código)`=NULL
Patentes$Origen=NULL
Patentes$Tipo=NULL
Patentes$V5=NULL
Patentes$V6=NULL
Patentes$V7=NULL
Patentes$V9=NULL
Patentes$V10=NULL
Patentes$V11=NULL
```


